<a href="https://colab.research.google.com/github/DpaolaMontes22/Programacionavanzada_parcial2/blob/main/EjercicioPiton14_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

UPIIH_PROGRAMACION AVANZADA

PROGRAMA QUE RESULVE EL PROBLEMA DE LAS 8 REINAS

Danna Paola Montes de Oca Hernandez 2021680104


In [6]:
ciclo=True
while ciclo:
 try:
     pass 
     print("Ingrese la posicion:")
     print("Fila:")
     x1 = int(input())
     print("Columna:")
     y1= int(input())

     if -1<y1<8 and -1<x1<8:
         ciclo=False
          
 except Exception:
     pass
     print("No es psotitivo!")  

import random
random.choice([1,2,3])
def disponibles(y,n):
    columnasDisponibles = []
    for x in range(n):
        if x1!=x and y1!=y:
            if(columna[x] or diagonalIzquierda[x+y] or diagonalDerecha[x-y+n-1]): 
                
                continue
            columnasDisponibles.append(x)
    return columnasDisponibles



if([]):
    print("y")
else:
    print("n")
    

n = 8
solucion = []

import numpy as np
tablero=np.zeros([8,8])

columna = [False]*n
diagonalIzquierda = [False]*(n*2)
diagonalDerecha = [False]*(n*2)

while(len(solucion)!=n and n>3):

    solucion = [(x1,y1)]
    columna = [False]*n
    diagonalIzquierda = [False]*(n*2)
    diagonalDerecha = [False]*(n*2)
    
    for y in range(n):
        if y1!=y:
           
            columnas_d = disponibles(y,n)
         
            if(columnas_d):
                x = random.choice(columnas_d)
            else:
                break
            
            columna[x] = diagonalIzquierda[x+y] = diagonalDerecha[x-y+n-1] = True
            solucion.append((x,y))
        
print(solucion)

for i in range(len(solucion)):
    ejes=solucion[i]
    tablero[ejes[0],ejes[1]]=1
print(tablero)

Ingrese la posicion:
Fila:
1
Columna:
1
n
[(1, 1), (6, 0), (5, 2), (2, 3), (0, 4), (3, 5), (7, 6), (4, 7)]
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
